########## Testcase 0: Failed ##########
Expected Output: 
76.8
6
Your Output: 
Traceback (most recent call last):
  File "week2.py", line 51, in <module>
    main()
  File "week2.py", line 19, in main
    nested_sum(data)
  File "week2.py", line 9, in nested_sum
    for x in item:
TypeError: 'int' object is not iterable
----------------------------------------
########## Testcase 1: Failed ##########
Expected Output: 
5.5
1
Your Output: 

----------------------------------------
########## Testcase 2: Failed ##########
Expected Output: 
1
6
Your Output: 
Traceback (most recent call last):
  File "week2.py", line 51, in <module>
    main()
  File "week2.py", line 19, in main
    nested_sum(data)
  File "week2.py", line 9, in nested_sum
    for x in item:
TypeError: 'int' object is not iterable
----------------------------------------
########## Testcase 3: Failed ##########
Expected Output: 
5
4
Your Output: 
Traceback (most recent call last):
  File "week2.py", line 51, in <module>
    main()
  File "week2.py", line 19, in main
    nested_sum(data)
  File "week2.py", line 9, in nested_sum
    for x in item:
TypeError: 'int' object is not iterable
----------------------------------------
########## Testcase 4: Failed ##########
Expected Output: 
0
8
Your Output: 
0
----------------------------------------
########## Testcase 5: Failed ##########
Expected Output: 
5654134.9
10
Your Output: 
Traceback (most recent call last):
  File "week2.py", line 51, in <module>
    main()
  File "week2.py", line 19, in main
    nested_sum(data)
  File "week2.py", line 9, in nested_sum
    for x in item:
TypeError: 'int' object is not iterable
----------------------------------------
